# Generated by Django 5.2.7 on 2025-10-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleModel',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
