# Generated by Django 5.2.7 on 2025-10-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('FOREIGNER', 'Foreigner'), ('BUSINESS', 'Business')], default='CITIZEN', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100),
        ),
    ]
