# Generated by Django 5.2.7 on 2025-10-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatmessage_conversation_chatmessage_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('MORTGAGE', 'Mortgage Loan'), ('AUTO', 'Auto Loan'), ('STUDENT', 'Student Loan'), ('BUSINESS', 'Business Loan')], default='PERSONAL', max_length=100)),
                ('repayment_methods', models.JSONField(default=dict, help_text='JSON field to store repayment methods', null=True)),
                ('purpose_description', models.TextField(blank=True, help_text='Description of the loan purpose', null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
